version: "3.7"

services:
  nginx:
    image: { { env.NGINX_IMAGE } }
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - backend

  backend:
    image: { { env.BACKEND_IMAGE } }
    restart: always
